name: Website

on:
  push:
    paths:
      - sparql-generate-website/**
    branches:
      - master

jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install and run gulp
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - run: |
          npm install
          gulp
        working-directory: sparql-generate-website

      - name: copy public
        uses: appleboy/scp-action@master
        with:
          source: "sparql-generate-website/public"
          target: "~/website"
          strip_components: 2
          host: ci.mines-stetienne.fr
          username: ${{ secrets.CI_USER }}
          key: ${{ secrets.CI_KEY }}

